---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-retry-deployment
  labels:
    app: go-retry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-retry
  template:
    metadata:
      labels:
        app: go-retry
    spec:
      containers:
        - name: go-retry
          image: alextanhongpin/go-retry:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
            - name: SERVICE_URL
              # This is the name of the server Service metadata name.
              value: http://go-server-service
---
apiVersion: v1
kind: Service
metadata:
  name: go-retry-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: go-retry
---
#https://linkerd.io/2/reference/service-profiles/
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: go-retry-service.default.svc.cluster.local
spec:
  routes:
    - name: GET /
      condition:
        method: GET
        pathRegex: /
      isRetryable: true ### ADD THIS LINE ###
  retryBudget:
    retryRatio: 0.2
    minRetriesPerSecond: 10
    ttl: 10s
