---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
  labels:
    app: go-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
      # This is required to make tracing work.
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/trace-jaeger: linkerd-jaeger.linkerd:14268
        config.alpha.linkerd.io/trace-jaeger-service-account: linkerd-jaeger
    spec:
      containers:
        - name: go-server
          image: alextanhongpin/go-server:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
            - name: JAEGER_AGENT_HOST
              value: http://linkerd-jaeger.linkerd:14268/api/traces
---
apiVersion: v1
kind: Service
metadata:
  name: go-server-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: go-server
